language: c
services:
  - docker
before_install:
  - docker pull alexignatyev/twitchxx:latest
  - docker run -v $PWD:/repo -itd --name build alexignatyev/twitchxx
script:
  - docker exec build cmake -H/repo -B/build
  - docker exec build cmake --build /build
notifications:
  recipients:
    - burannah@gmail.com
  email:
    on_success: change
