language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    packages:
    # install toolchains
    - gcc
    - g++
    - cmake-data
    - cmake

before_install:
 - sudo apt-get install libboost-regex-dev libboost-system-dev libboost-thread-dev libboost-test-dev libboost-random-dev libcpprest-dev -y
env:
  global:
    - BOOST_INCLUDES=/usr/include
    - BOOST_LIBS=/usr/lib
before_script:
   - mkdir bin
   - cd bin
   - cmake ..

script: make

branches:
  only:
    - master
notifications:
  recipients:
    - burannah@gmail.com
  email:
    on_success: change
    on_failure: always
